### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by NecmiKaan07** [EyuphanMandiraci/mpdb#2]
![Screenshot_59](https://user-images.githubusercontent.com/85132062/120232900-36ad3480-c25d-11eb-9bdf-153553c8ccc9.png)
Discord tuşuna basınca linke yönlendiriyor ama linkte "Invite Invalid" yazıyor

**Comment by EyuphanMandiraci** [comment]
Muhtemelen sunucudaki kanalları silip yeniden oluşturunca link bozuldu bir sonraki betada düzeltilecektir.

**Comment by NecmiKaan07** [comment]
![Screenshot_61](https://user-images.githubusercontent.com/85132062/120235488-cc978e00-c262-11eb-8729-250f26456131.png)
Windows 10 Pro
